export const lightTheme = {
  background: '#fff',
  color: '#121212',
  accentColor: '#3D84C6',
  chronoTheme: {
    cardBgColor: 'white',
    cardForeColor: 'black',
    titleColor: 'white',
  },
  timelineLineColor: '#ccc',
  cardBackground: '#fff',
  cardFooterBackground: '#f7f7f7',
  cardBorderColor: '#00000020',
  navbarTheme: {
    linkColor: '#dedede',
    linkHoverColor: '#fefefe',
    linkActiveColor: '#fefefe',
  },
  bsPrimaryVariant: 'light',
  bsSecondaryVariant: 'dark',
  socialIconBgColor: '#121212',
  buttonPrimaryBgColor: '#3D84C6',
  buttonPrimaryTextColor: '#fff',
  buttonSecondaryBgColor: '#F2F2F2',
  buttonSecondaryTextColor: '#121212',
  sectionTitleColor: '#000',
  sectionSubtitleColor: '#555',
  sectionDividerColor: '#ccc',
  boxShadow: '0 5px 15px rgba(0, 0, 0, 0.1)',
  gradient: 'linear-gradient(to right, #3D84C6, #FF5F6D)',
  hoverEffect: 'scale(1.05)',
  transitionDuration: '0.3s',
};

export const darkTheme = {
  background: '#121212',
  color: '#eee',
  accentColor: '#3D84C6',
  chronoTheme: {
    cardBgColor: '#1B1B1B',
    cardForeColor: '#eee',
    titleColor: 'black',
  },
  timelineLineColor: '#444',
  cardBackground: '#060606',
  cardFooterBackground: '#181818',
  cardBorderColor: '#ffffff20',
  navbarTheme: {
    linkColor: '#dedede',
    linkHoverColor: '#fefefe',
    linkActiveColor: '#fefefe',
  },
  bsPrimaryVariant: 'dark',
  bsSecondaryVariant: 'light',
  socialIconBgColor: '#fefefe',
  buttonPrimaryBgColor: '#3D84C6',
  buttonPrimaryTextColor: '#fff',
  buttonSecondaryBgColor: '#1B1B1B',
  buttonSecondaryTextColor: '#eee',
  sectionTitleColor: '#eee',
  sectionSubtitleColor: '#aaa',
  sectionDividerColor: '#666',
  boxShadow: '0 5px 15px rgba(0, 0, 0, 0.5)',
  gradient: 'linear-gradient(to right, #FF5F6D, #FFC371)',
  hoverEffect: 'scale(1.1)',
  transitionDuration: '0.5s',
};
